apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cloudshield-gateway
spec:
  gatewayClassName: cloudshield-gatewayclass-controller
  listeners:
    - name: https-mlflow
      protocol: HTTPS
      port: 443
      hostname: mlflow.local
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: flower-server-certs

    - name: https-prediction-api
      protocol: HTTPS
      port: 443
      hostname: api.local
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: flower-server-certs

    - name: https-grafana
      protocol: HTTPS
      port: 443
      hostname: grafana.local
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: flower-server-certs

    - name: node-api
      protocol: HTTPS
      port: 9092
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: flower-server-certs

    - name: control-api
      protocol: HTTPS
      port: 9093
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: flower-server-certs
