apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: superlink-backend-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: superlink-service
  validation:
    hostname: "superlink"
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: superlink-ca-configmap
