apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: default
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command:
            - mlflow
            - server
          args:
            - --backend-store-uri
            - sqlite:////app/server_k8s/mlflow_data/mlflow.db
            - --default-artifact-root
            - /app/server_k8s/mlflow_data/artifacts
            - --host
            - 0.0.0.0
            - --port
            - "8080"
          env:
            - name: MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE
              value: "true"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: mlflow-storage
              mountPath: /app/server_k8s/mlflow_data
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc
