apiVersion: apps/v1
kind: Deployment
metadata:
  name: superlink-deployment
  labels:
    app: superlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superlink
  template:
    metadata:
      labels:
        app: superlink
    spec:
      containers:
        - name: superlink
          image: flwr/superlink:latest
          command: ["flower-superlink"]
          args:
            - "--ssl-ca-certfile=/etc/flwr/config/ca.crt"
            - "--ssl-certfile=/etc/flwr/certs/tls.crt"
            - "--ssl-keyfile=/etc/flwr/certs/tls.key"
            - "--enable-supernode-auth"
            - "--isolation"
            - "process"
          ports:
            - containerPort: 9091
            - containerPort: 9092
            - containerPort: 9093
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flwr/config
              readOnly: true
            - name: tls-secret-volume
              mountPath: /etc/flwr/certs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: superlink-ca-configmap
        - name: tls-secret-volume
          secret:
            secretName: flower-server-certs
