apiVersion: v1
kind: Service
metadata:
  name: superlink-service
spec:
  type: ClusterIP
  selector:
    app: superlink
  ports:
    - name: exec-api
      port: 9091
      targetPort: 9091
    - name: node-api
      port: 9092
      targetPort: 9092
    - name: control-api
      port: 9093
      targetPort: 9093